# Generated by Django 5.0.6 on 2024-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='APIs.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_list', to='APIs.profile'),
        ),
    ]
